modLoader="javafml"
loaderVersion="[33,)" 

author="fubira"
license="Copyright (c) 2016-2020 fubira"

issueTrackerURL="https://github.com/fubira/FlightView/issues"

[[mods]]
modId="flightview"
version="${file.jarVersion}"
displayName="FlightView"
displayURL="https://github.com/fubira/FlightView/"
credits="fubira/KenmoMinecraftClub"
author="fubira"

description='''
FlightView
'''

[[dependencies.flightview]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.flightview]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

