modLoader="javafml"
loaderVersion="[31,)" 

author="fubira"
issueTrackerURL="https://github.com/fubira/FlightView/issues"

[[mods]]
modId="flightview"
version="${file.jarVersion}"
displayName="FlightView"
displayURL="https://github.com/fubira/FlightView/"
credits="fubira/KenmoMinecraftClub"
author="fubira"

description='''
FlightView
'''

[[dependencies.flightview]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.flightview]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

