version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.8
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: ./gradlew dependencies
      - run: ./gradlew build

      - store_artifacts:
          path: build/libs
