[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version = "1.19" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.14.6" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.56.1+1.19" }
forge = { group = "net.minecraftforge", name = "forge", version = "1.19-41.0.45" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version = "7.0.72" }
clothConfigForge = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version = "7.0.72" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.9.0" }
log4japi = { group = "org.apache.logging.log4j", name = "log4j-api", version = "2.17.2" }
log4jcore = { group = "org.apache.logging.log4j", name = "log4j-core", version = "2.17.2" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]
