[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version = "1.18.1" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.12.12" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.45.0+1.18" }
forge = { group = "net.minecraftforge", name = "forge", version = "1.18.1-39.0.10" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version = "6.1.48" }
clothConfigForge = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version = "6.1.48" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.8.9" }
log4japi = { group = "org.apache.logging.log4j", name = "log4j-api", version = "2.15.0" }
log4jcore = { group = "org.apache.logging.log4j", name = "log4j-core", version = "2.15.0" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]
