[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version = "1.17.1" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.11.6" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.37.1+1.17" }
forge = { group = "net.minecraftforge", name = "forge", version = "1.17.1-37.0.27" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version = "5.0.38" }
clothConfigForge = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version = "5.0.38" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.8.6" }
log4japi = { group = "org.apache.logging.log4j", name = "log4j-api", version = "2.14.1" }
log4jcore = { group = "org.apache.logging.log4j", name = "log4j-core", version = "2.14.1" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]
