modLoader = "${modloader}"
loaderVersion = "${modloader_version_range}"

author = "${mod_authors}"
license = "${mod_license}, Copyright (c) ${mod_vendor}"
issueTrackerURL = "https://github.com/fubira/FlightView/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/fubira/FlightView/"
credits = "${mod_vendor}"
author = "${mod_authors}"

description = '''
${mod_description}
'''

[[dependencies.flightview]]
    modId = "minecraft"
    mandatory = true
    versionRange="${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.flightview]]
    modId = "neoforge"
    mandatory = true
    versionRange="${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"
