modLoader = "javafml"
loaderVersion = "${fml_loader_version_range}"

author = "${authors}"
license = "${license}, Copyright (c) ${vendor}"
issueTrackerURL = "https://github.com/fubira/FlightView/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://github.com/fubira/FlightView/"
credits = "${vendor}"
author = "${authors}"

description = '''
FlightView
'''

[[dependencies.flightview]]
    modId = "minecraft"
    mandatory = true
    versionRange="${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.flightview]]
    modId = "neoforge"
    mandatory = true
    versionRange="${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"
