name: Build

on:
  push:
    branches: [ main, develop, update-to-* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
      env:
        JVM_OPTS: -Xmx3200m
    
    - name: Upload Fabric artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fabric-artifacts
        path: fabric/build/libs/*.jar
        if-no-files-found: error
    
    - name: Upload NeoForge artifacts
      uses: actions/upload-artifact@v4
      with:
        name: neoforge-artifacts
        path: neoforge/build/libs/*.jar
        if-no-files-found: error
    
    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: |
          build/reports
          fabric/build/reports
          neoforge/build/reports
        if-no-files-found: ignore